### PR TITLE
Event validation

### PR DESCRIPTION
**Pull request by scott-wyatt**
@poacher2k this is Event Validation as the lifecycle hook to answer #4, thoughts on this approach?

### CODE REVIEW

**Comment by poacher2k** [comment]
This looks awesome!

A thought: Is there any possibility at all that someone would be able to get an event id before it reaches the server from Stripe, and send malicious data to the server? If yes, then the event validation would pass, but the data fed could potentially cause harm. Overwriting the `POST`ed event's values with the data we get back from the event validation could safeguard us, but if this is unrealistic, then the overhead may be a bit unecessary.

**Comment by scott-wyatt** [comment]
It's true, since there isn't 2-way authorization on the system there is always a chance of an intercept. More or less though, it seems that their would need to be malicious code on the server to intercept the event id and then eject bunk data.  We could do a compare of the data but if a user already can intercept the event id, they may already be able to intercept the outgoing call as well.

**Comment by poacher2k** [comment]
Good point. This seems only theoretically possible, so it's probably a good idea to do it as you approach it in this PR.

**Comment by scott-wyatt** [comment]
Okay, this is PR is now available on NPM.

**Comment by poacher2k** [comment]
Awesome! Thanks for your good work.

**Pull request merged**
